-- Drop tables in the reverse order of creation to handle foreign key dependencies

DROP TABLE IF EXISTS COMMENT_VOTES;
DROP TABLE IF EXISTS USER_FRONT_PAGE;
DROP TABLE IF EXISTS COMMUNITY_POSTS;
DROP TABLE IF EXISTS POST_COMMENTS;
DROP TABLE IF EXISTS POST_VOTES;
DROP TABLE IF EXISTS COMMUNITY_MODERATOR;
DROP TABLE IF EXISTS COMMUNITY_MEMBERS;
DROP TABLE IF EXISTS MB_SESSION;
DROP TABLE IF EXISTS CREATE_COMMENT;
DROP TABLE IF EXISTS COMMENTS;
DROP TABLE IF EXISTS CREATE_COMMENT;
DROP TABLE IF EXISTS CREATE_POST;
DROP TABLE IF EXISTS POST_FLAIR;
DROP TABLE IF EXISTS POST;
DROP TABLE IF EXISTS COMMUNITY;
DROP TABLE IF EXISTS MB_USER;

DROP TRIGGER IF EXISTS MEMBER_FRONT_PAGE_TRIGGER;
DROP TRIGGER IF EXISTS MOD_MEMBER_TRIGGER;

-- Finally, drop the database
-- DROP DATABASE IF EXISTS messageBoard;